---
title: "FraudulentConveyance"
author: "Michael Szczepaniak"
date: "September 1, 2015"
output: html_document
---

## A Story of How Statistics Was Used to Prove Fraud

From 2007 through Spring of 2012, a company I founded, Canadian Venture Partners (CVP) filed a legal claim against a Canadian POS services provider which I'll refer to as Company X or **CX** for short to protect their anonymity.

```{r echo = FALSE}
options(scipen = 3, digits = 2)
judgment <- 316602.17 +
             91898.71 +
             14463.59 +
             90276.14 +
             19993.87 +
            105795.00 +
             18832.50 +
             18832.50 +
             10495.51
```

In June of 2007, CVP obtained a judgment against CX in the amount of $`r judgment` CAD.  During the collections process, CX claimed that it had no money or assets to pay the judgment.  Upon analysis of records obtained during examination of the president of CX (who will be referred to as Mr. CX), I concluded that CX had transferred its merchant client base to another company controlled by Mr. CX.  This initial analysis was compelling enough for me and CVP's legal council (LC) to file a fraudulent conveyance action (FCA) against Mr. CX. and his accomplices in the summer of 2007.

In order to successfully litigate a FCA as a plaintiff, two important criteria need to be met:

1. First, it must be proven that assets were fraudulently conveyed by the defendant in order to unlawfully avoid payment of obligations owed the plaintiff(s).
2. Second, after establishing that fraudulent conveyance had taken place, the amount of the fraud must be quantified.  This second criteria is necessary in order establish a basis (referred to as the **quanta** in legal parlance) from which the judge can decide on the amount to award the plaintiff(s).

This initial analysis was focused on the first criteria of building the evidence base establishing a solid argument that fraudulent conveyance had been committed while accomplishing two important complimentary objectives.  The first being to convince LC to take CVP's case based on contingency.  This was necessary because neither CVP, myself, or any of the co-plaintiffs had the resources to finance a multi-year lawsuit conducted in a foreign country (Canada).  The second was to establish a solid base from which future analysis primarily focused on the second criteria of quantifying the amount of the fraud could be conducted.